#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --gpus-per-node=1
#SBATCH --job-name=deap_DEF
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=RunMethod_%A_boxplots.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# pip install deap
# pip install neat-python
# pip install pandas
# pip install pygame


#python optimization_generalist_NEAT_optuna.py

python plot_boxplot.py

